kind: pipeline
type: kubernetes
name: MrFriendly Dashboard Docker Image

triggers:
  event:
  - cron
  cron:
  - nightly
  branch:
  - master

steps:
  - name: Build the Docker image
    image: plugins/docker
    settings:
      repo: registry.thedutchmc.nl/mrfriendly-dashboard
      tags:
      - latest
      registry: registry.thedutchmc.nl

  - name: Deploy to Kubernetes
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl set image deployment/dashboard dashboard=registry.thedutchmc.nl/mrfriendly-dashboard:latest -n mrfriendly
      
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: discord_webhook
      username: Drone CI/CD - MrFriendly Dashboard Docker Image 
    when:
      status: [ success, failure ]