kind: pipeline
type: kubernetes
name: MrFriendly Dashboard Docker Image

trigger:
  branch:
  - master

steps:
  - name: Build the Docker image
    image: plugins/docker
    settings:
      repo: docker-registry.k8s.array21.dev/mrfriendly-dashboard
      tags:
      - latest
      registry: docker-registry.k8s.array21.dev

  - name: Deploy to Kubernetes
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl set image deployment/dashboard dashboard=docker-registry.k8s.array21.dev/mrfriendly-dashboard:latest -n mrfriendly
      
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: discord_webhook
      username: Drone CI/CD - MrFriendly Dashboard Docker Image 
    when:
      status: [ success, failure ]
