kind: pipeline
type: kubernetes
name: build-latest

trigger:
  branch:
  - master

steps:
- name: Build Docker
  image: plugins/docker
  resources:
    limits:
      cpu: 6000
  settings:
    repo: docker-registry.k8s.array21.dev/mrfriendly-dashboard
    tags:
    - latest
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - MrFriendly Dashboard - build-latest
  when:
    status: [ failure ]
---
kind: pipeline
type: kubernetes
name: build-release

trigger:
  event:
  - tag

steps:
- name: Build Docker
  image: plugins/docker
  resources:
    limits:
      cpu: 6000
  settings:
    repo: docker-registry.k8s.array21.dev/mrfriendly-dashboard
    registry: docker-registry.k8s.array21.dev
    tags:
    - ${DRONE_TAG}
    - latest

- name: Deploy to Kubernetes
  image: ubuntu:latest
  environment:
    DEBIAN_FRONTEND: noninteractive
    SSH_KEY:
      from_secret: ssh_key
    
  commands:
  - apt update && apt install -y openssh-client
  
  - mkdir -p $HOME/.ssh/
  - eval `ssh-agent`
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null

  - rm -rf $HOME/.ssh/config
  - touch $HOME/.ssh/config
  - echo "Host *\n\tStrictHostKeyChecking no" > $HOME/.ssh/config
  
  - "ssh droneci@kube-ssh.intern.array21.dev kubectl set image -n mrfriendly deployment/dashboard dashboard=docker-registry.k8s.array21.dev/mrfriendly-dashboard:${DRONE_TAG}"

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Twinsight MrFriendly Dashboard - build-release
  when:
    status: [ failure ]
---
kind: pipeline
type: kubernetes
name: build-and-test

trigger:
  event:
  - pull_request
  - push

steps:
- name: NPM
  image: node:16-buster
  resources:
    limits:
      cpu: 2000
  commands:
  - npm i
  - npx webpack

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - MrFriendly Dashboard - build-and-test
  when:
    status: [ failure ]